'use client';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { Activity, ArrowUpRight, Bell as BellIcon, BrainCircuit, ChevronRight, CircleAlert, Menu, Route as RouteIcon, ShieldCheck, SlidersHorizontal, X } from 'lucide-react';
import { getData, postData } from '../../lib/api';
const WorldMap = dynamic(() => import('../../components/map/WorldMap'), { ssr: false, loading: () => <div className="min-h-[600px] animate-pulse rounded-lg border border-[#26323d] bg-[#10242c]" /> });

type Country = { id: string; name: string; score: number; band: string; lat: number; lng: number };
type RouteData = { id: string; name: string; from: string; to: string; risk: number; capacity: number; cost: number; transit_days: number; chokepoint: string };
type Global = { score: number; band: string; change_24h: number };
type Simulation = { supply_deficit_percent: number; cost_increase_percent: number; reserve_days_remaining: number; affected_routes: number; mitigation: string };
const colors: Record<string, string> = { Low: '#42d3c5', Moderate: '#8ccf9b', Elevated: '#f3b45b', High: '#f18b5b', Critical: '#f16b6b' };
const Bell = (props: any) => <BellIcon {...props} />;

function Metric({ label, value, detail, accent = '#e8edf2' }: { label: string; value: string; detail: string; accent?: string }) {
  return <div className="panel min-w-0 p-4"><div className="flex items-center justify-between text-[10px] uppercase tracking-[.16em] text-[#8995a3]"><span>{label}</span><Activity size={13} color={accent} /></div><div className="mt-3 text-2xl font-extrabold" style={{ color: accent }}>{value}</div><div className="mt-1 text-xs text-[#8995a3]">{detail}</div></div>;
}

export default function Dashboard() {
  const [global, setGlobal] = useState<Global | null>(null); const [countries, setCountries] = useState<Country[]>([]); const [routes, setRoutes] = useState<RouteData[]>([]); const [alerts, setAlerts] = useState<any[]>([]); const [simulation, setSimulation] = useState<Simulation | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([getData<Global>('/api/risk/global'), getData<Country[]>('/api/countries'), getData<RouteData[]>('/api/routes'), getData<any[]>('/api/alerts')]).then(([g, c, r, a]) => { setGlobal(g); setCountries(c); setRoutes(r); setAlerts(a); }).catch(() => { }).finally(() => setLoading(false)); }, []);
  const runDemo = () => postData<Simulation>('/api/scenarios/simulate', { scenario: 'hormuz_closure', duration_days: 14, severity: 75 }).then(setSimulation);
  return <main className="min-h-screen"><header className="flex items-center justify-between border-b border-[#26323d] bg-[#0c151c] px-5 py-4 lg:px-8"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded bg-[#42d3c5] text-[#071115]"><ShieldCheck size={21} /></div><div><div className="text-sm font-extrabold tracking-[.14em]">GEOSHIELD</div><div className="mono text-[9px] text-[#8995a3]">RISK INTELLIGENCE / 04.18Z</div></div></div><nav className="hidden gap-8 text-xs text-[#8995a3] md:flex"><a className="border-b-2 border-[#42d3c5] pb-4 text-white" href="/">COMMAND CENTER</a><a className="hover:text-white" href="/scenario">SCENARIO LAB</a><a className="hover:text-white" href="/analytics">ANALYTICS</a></nav><div className="flex items-center gap-4"><span className="hidden items-center gap-2 text-[10px] uppercase tracking-widest text-[#42d3c5] sm:flex"><span className="h-2 w-2 animate-pulse rounded-full bg-[#42d3c5]" /> Demo Mode</span><Bell size={17} color="#8995a3" title="Notifications" /><Menu className="md:hidden" size={18} /></div></header>
    <section className="mx-auto max-w-[1600px] p-5 lg:p-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-[10px] uppercase tracking-[.2em] text-[#42d3c5]"><span className="h-px w-8 bg-[#42d3c5]" /> Executive view</div><h1 className="text-3xl font-extrabold tracking-tight">Global Risk Command Center</h1><p className="mt-2 text-sm text-[#8995a3]">A decision layer for supply chain exposure, disruption, and response.</p></div><div className="flex gap-2"><button className="flex items-center gap-2 border border-[#34444d] px-3 py-2 text-xs text-[#c4d0d6] hover:border-[#42d3c5]"><SlidersHorizontal size={14} /> Configure view</button><button onClick={runDemo} className="flex items-center gap-2 bg-[#42d3c5] px-3 py-2 text-xs font-bold text-[#071115] hover:bg-[#70e0d5]"><BrainCircuit size={14} /> Run scenario</button></div></div>
      <div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{loading ? <div className="col-span-4 py-10 text-center text-sm text-[#8995a3]">Connecting to intelligence service...</div> : <><Metric label="Global risk score" value={`${global?.score}`} detail={`▲ ${global?.change_24h}% vs 24h ago`} accent={colors[global?.band || 'Elevated']} /><Metric label="Supply chain health" value="71%" detail="29% capacity at risk" accent="#42d3c5" /><Metric label="Critical routes" value={`${routes.filter(r => r.risk > 60).length}`} detail="2 require action today" accent="#f16b6b" /><Metric label="Active alerts" value={`${alerts.length}`} detail="Across 7 regions" accent="#f3b45b" /></>}</div>
      <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.7fr)_minmax(300px,.75fr)]"><WorldMap countries={countries} routes={routes} scenarioActive={Boolean(simulation)} /><aside className="panel p-5"><div className="mb-5 flex items-center justify-between"><h2 className="text-sm font-bold">Priority signals</h2><span className="mono text-[10px] text-[#8995a3]">UPDATED 04:18Z</span></div>{alerts.slice(0, 4).map(a => <div key={a.id} className="mb-4 flex gap-3 border-b border-[#26323d] pb-4 last:border-0"><CircleAlert size={16} color={a.severity === 'High' ? '#f16b6b' : '#f3b45b'} /><div><div className="text-xs font-bold">{a.title}</div><div className="mt-1 text-[11px] leading-relaxed text-[#8995a3]">{a.type} signal across {a.countries.join(', ')}</div></div></div>)}<div className="mt-3 flex items-center gap-2 text-xs text-[#42d3c5]">View all intelligence <ChevronRight size={13} /></div></aside></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><section className="panel p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-bold">Critical supply routes</h2><p className="mt-1 text-xs text-[#8995a3]">Corridors ranked by exposure and concentration</p></div><RouteIcon size={18} color="#8995a3" /></div><div className="space-y-3">{routes.slice(0, 4).map(r => <div key={r.id} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 border-t border-[#26323d] pt-3"><div><div className="text-xs font-bold">{r.name}</div><div className="mono mt-1 text-[10px] text-[#8995a3]">{r.chokepoint} · {r.transit_days} days transit</div></div><div className="w-24"><div className="mb-1 flex justify-between text-[10px] text-[#8995a3]"><span>RISK</span><span>{r.risk}</span></div><div className="h-1 bg-[#26323d]"><div className="h-1" style={{ width: `${r.risk}%`, background: r.risk > 60 ? '#f16b6b' : '#f3b45b' }} /></div></div><span className="mono text-xs text-[#f3b45b]">{r.capacity}kt</span></div>)}</div></section><section className="panel p-5"><div className="mb-4 flex items-center gap-2"><BrainCircuit size={17} color="#42d3c5" /><h2 className="text-sm font-bold">AI intelligence brief</h2></div><p className="text-sm leading-7 text-[#c4d0d6]">Signals indicate concentrated exposure around Gulf energy lanes and a manageable but rising logistics risk. Diversification is available, but alternative capacity is tightening.</p><div className="mt-5 border-l-2 border-[#42d3c5] pl-3 text-xs leading-6 text-[#8995a3]">Synthetic demo analysis. Numerical risk and impact calculations are deterministic.</div><button className="mt-5 flex items-center gap-2 text-xs font-bold text-[#42d3c5] hover:text-white">Open analysis <ArrowUpRight size={14} /></button></section></div>
      {simulation && <div className="panel mt-5 border-[#f3b45b] p-5"><div className="flex items-start justify-between"><div><div className="text-[10px] uppercase tracking-widest text-[#f3b45b]">Simulation complete</div><h2 className="mt-2 text-lg font-bold">Strait of Hormuz closure · 14 days</h2></div><button onClick={() => setSimulation(null)} aria-label="Close simulation"><X size={16} /></button></div><div className="mt-5 grid grid-cols-2 gap-4 md:grid-cols-4"><Metric label="Supply deficit" value={`${simulation.supply_deficit_percent}%`} detail="of modeled capacity" accent="#f16b6b" /><Metric label="Cost increase" value={`${simulation.cost_increase_percent}%`} detail="transport estimate" accent="#f3b45b" /><Metric label="Reserve remaining" value={`${simulation.reserve_days_remaining}d`} detail="before stockout" accent="#42d3c5" /><Metric label="Routes affected" value={`${simulation.affected_routes}`} detail="network corridors" accent="#f16b6b" /></div><div className="mt-4 text-xs text-[#c4d0d6]">{simulation.mitigation}</div></div>}</section></main>;
}
